Add option to disable threadpool - Add retryAfterSeconds - Disable UPnP actions for HTTPS
jupnp/jupnp pull request #129
Opened 2021-02-03 23:26 UTC by morph166955

Adds option to disable threadpools for large UPnP environments.

Disable all UPnP action calls based on HTTPS - Fixed #109

From openhab/openhab-addons#5892

Mentioned in https://community.openhab.org/t/panasonictv-oh3/108124
https://community.openhab.org/t/too-much-time-before-a-sonos-thing-becomes-definitively-online/62214

New setting retryAfterSeconds

New setting maxRequests to trigger an automatic restart of the router after a certain number of executed requests

retryAfterSeconds and maxRequests code written by: lolodomo - merged into this branch by morph166955

Signed-off-by: morph166955 rosenblumb@gmail.com

2021-02-05 01:50 UTC, morph166955 commented
For anyone looking to test. 

https://github.com/morph166955/jupnp/releases/tag/8392ab9

Valid config options (values are examples):

org.jupnp:retryAfterSeconds=10

org.jupnp:asyncThreadPoolSize=60
org.jupnp:threadPoolSize=30
org.jupnp:remoteThreadPoolSize=60

org.jupnp:asyncThreadPool=false
org.jupnp:mainThreadPool=false
org.jupnp:remoteThreadPool=false

NOTE: all ThreadPoolSize options are obviously irrelevant if the threadpool is disabled (set to false).

2021-02-27 03:19 UTC, morph166955 commented
@kaikreuzer Requesting your review of this please.  It would be great if this could be released so it could be updated on the OH side as part of the 3.1 release.  I believe there are a good sized number of users that this would benefit.  Thank you in advance for your time!

2021-02-28 19:30 UTC, morph166955 commented
@kaikreuzer As per request, itemizing what this resolves.

1) retryAfterSeconds and maxRequests address issues where the system loses track of a device (because of a variety of reasons) and then only attempts to reestablish connection by default at the 10 minute mark.  This is entirely too long for a device to be offline.  These configuration items allow for a user to specify a reduced time.  While we could dial this down statically, that doesn't provide end users with flexibility.  This allows for them to specify what they need for their specific application if they run into this issue.

2) Resolves errors in https://github.com/jupnp/jupnp/issues/109 by disabling HTTPS UPnP calls (which I believe are not in alignment with the UPnP spec although I can't find the specific document that says that).  

3) Race conditions seem to happen in bursty situations.  For example, massive unsubscribe requests fill up the thread pool.  This has shown instances where the replys from the unsubscribes aren't actually processed and we end up waiting for the timeouts to occur.  Real world example is https://github.com/openhab/openhab-core/issues/1886.  In that case, during shutdown there is a burst of unsubscribes which fills up the pool and is causing the system to hang.  This seems to be associated to the async threadpool directly.  The remote registry seems to also cause issues in times of bursts.  The changes to the threadpool logic does the following

4) There is no way to control the upnp traffic on a network.  Every device that has a upnp library will broadcast unless disabled. 
 Even if the user only uses one device through jupnp, the library still receives and processes data from every upnp device that is broadcasting on the network.  This can also cause issues of thread contention and bursty situations.  Being able to adjust the threadpools (or disable them) can help handle situations where the network itself is causing the issue and not the "actual use of the library".

-Splits off the remote registry into a third group of threads (so now it's main, async, and remote).
-Each pool can now be disabled so that it can create single threads for everything that it does.  This removes all contention.  The obvious downside is that memory and cpu usage can/will spike.  This is set as a configurable option so that users who have the resources and are running into the issues can flip the switch.  
-For users who don't have the resources to go single thread, they can dial up the specific pool.  Having remote registry split off gives those users a bit more flexibility without completely removing the boundaries of the pools. 
-If operating in a "single thread mode", threads are created using the name of the process that is creating it.  All threads start with "upnp-" and are followed by part of the code (e.g. "upnp-notification" or "upnp-subscribe").  This can help with troubleshooting to quickly identify which part of the system is bursting the thread creation/contention.

2021-02-28 20:16 UTC, morph166955 commented
One last note, above notes a force push of 8392ab9 to 13d8a79, that just fixed DCO by adding sign-off to the commit and had no impact on the code.  Hence why the jar is for 8392ab9.

2021-03-07 00:32 UTC, morph166955 commented
All build errors are now resolved.

2021-03-15 17:41 UTC, morph166955 commented
@kaikreuzer Please hold on hitting the final merge button on this.  I have one more commit that fixes/adds #130.  It won't impact the functionality of this code so you're still more than welcome to review the commits so far.  Adding it into this PR will make merging easier as it adds to some of the work that retryAfterSeconds does and I would have conflicts otherwise.

2021-03-16 01:46 UTC, morph166955 commented
Ok, good now.  I added item 5 in the post above to explain.  Build looks clean.  This is good from my side to be merged.

2021-03-16 15:50 UTC, morph166955 commented
There seems to be an issue with the https filter.  I noticed this morning I'm still getting errors periodically.  Apparently in some instances it's never making it to the check, it throws an error before that.  I think I see where it needs to be fixed.  I'll try to throw some extra code in later for it.

2021-03-17 02:02 UTC, morph166955 commented
HTTPS filter fixed.  

Before:

```
2021-03-16 20:39:18.757 [TRACE] [org.jupnp.transport.spi.StreamClient] - Preparing HTTP request: (StreamRequestMessage) GET https://REDACTED:8888/capability
2021-03-16 20:39:18.757 [TRACE] [org.jupnp.transport.spi.StreamClient] - Creating HTTP request. URI: 'https://REDACTED:8888/capability' method: 'GET'
2021-03-16 20:39:18.757 [TRACE] [org.jupnp.transport.spi.StreamClient] - Waiting 2 seconds for HTTP request to complete: (StreamRequestMessage) GET https://REDACTED:8888/capability
2021-03-16 20:39:18.757 [TRACE] [org.jupnp.transport.spi.StreamClient] - Sending HTTP request: (StreamRequestMessage) GET https://REDACTED:8888/capability
2021-03-16 20:39:18.758 [WARN ] [org.jupnp.transport.spi.StreamClient] - HTTP request failed: (StreamRequestMessage) GET https://REDACTED:8888/capability
```

After:

```
2021-03-17 02:01:18.980 [TRACE] [org.jupnp.transport.spi.StreamClient] - Preparing HTTP request: (StreamRequestMessage) GET https://REDACTED:8888/capability
2021-03-17 02:01:18.989 [DEBUG] [org.jupnp.transport.spi.StreamClient] - HTTPS invalid.  Ignoring call https://REDACTED:8888/capability.

```

2021-03-17 02:14 UTC, morph166955 commented
JAR available at https://github.com/morph166955/jupnp/releases/tag/0d57595 for testing.

2021-03-21 11:34 UTC, kaikreuzer commented
@morph166955 This has become quite a large PR and I am honestly not feeling able to easily understand which code change is related to which problem. I am really cautious in doing changes to jUPnP, because it is very easy to break things and not make it compliant to the specs anymore.

I'd very much prefer to have dedicated PRs per issue that is to be fixed by it. This makes reviewing much easier and it also gives a chance to roll-back single changes in case it turns out that they cause problems.

Do you see a chance to split this into 3-5 independent PRs?

2021-03-21 12:38 UTC, morph166955 commented
I'll do what I can to split it up. A few things, yes we can carve off, like disabling https which is relatively standalone. The problem is that others make changes to the same line (e.g. createStreamClient) so splitting will be very complicated.

2021-03-21 15:14 UTC, morph166955 commented
@kaikreuzer I pulled the https piece out and submitted #131 for that.  

Otherwise, I've been trying to separate this out and I'm having issues pulling it apart because of lines like: 

https://github.com/jupnp/jupnp/blob/30e2d1174158ba1c0de067d51c68985cad68beae/bundles/org.jupnp/src/main/java/org/jupnp/OSGiUpnpServiceConfiguration.java#L209

In this example, we are calling getSyncProtocolExecutorService("upnp-stream") and are adding the "upnp-stream" string for the thread name but we're also adding "retryAfterSeconds,retryIterations,timeoutSeconds" to support those changes.  I suppose we could pull the threadpool changes into one PR, commit those changes, and then add the "retryAfterSeconds,retryIterations,timeoutSeconds" as a second PR after the first one is committed so that it diff's properly.  That said, it would really only break the PR into two pieces.  

The changes left in this PR are really broken into two groups:
1) Modification to the threadpool code which is the majority of the changes that add "String threadName" to a bunch of function calls and then the changes to OSGiUpnpServiceConfiguration.java which actually handle the thread creation/usage.
2) Modification to AbstractStreamClient.java (and a few associated files) which add retryAfterSeconds, retryIterations, timeoutSeconds.

I don't see how either of these would modify or make this uncompliant to the upnp spec.  The threadpool changes are dealing with how we handle the threads, which have nothing to do with how we communicate with the devices, only how we handle the threads.  The other changes only deal with how long we wait, and how many times we try to make connections before failing.  

Thoughts?

2021-03-21 15:48 UTC, morph166955 commented
I'll correct one statement above, I forgot about maxRetries and have pulled that out and will submit a separate PR for it.

2021-03-21 16:15 UTC, morph166955 commented
I've updated the descriptions above to remove the pieces pulled off to different PRs.

2021-03-21 16:25 UTC, kaikreuzer commented
Don't forget the issue title ;-)

2021-03-21 16:28 UTC, morph166955 commented
Title updated!  ;-)

2021-03-21 16:32 UTC, kaikreuzer commented
The title seems to suggest that the PR still contains two very independent changes. Is this the case or is there any logical dependency between the two features?

2021-03-21 16:38 UTC, morph166955 commented
There are two sets of changes here.  The problem is that it will be very hard for me to separate them due to the changes to createStreamClient.  createStreamClient requires the sending of the executor service as well as the contents of the 3 variables as part of the call.  Since these changes all happen on the same line, it will be hard for me to diff them out.  I considered pulling the executor service off and store it in a variable, and then sending that, but it doesn't fix the problem either.  I think the only way I could do it would be to commit the threadpool changes, and then submit a PR for the other changes so that it diffs properly.  Totally open to suggestions here, I am by far not a git master.

2021-03-21 17:04 UTC, kaikreuzer commented
If they really only share one line, I think it would be great to take them apart.
Feel free to first do a PR for the thread handling and once this is merged (and yes, I promise to review and discuss right away), do the other one on top.

2021-03-21 17:05 UTC, morph166955 commented
Ok.  I'll pull the bits out right now, you should have a commit in a few minutes.

2021-03-21 17:21 UTC, morph166955 commented
@kaikreuzer This is now ONLY the threadpool code.  I'll update the info above but I believe the code itself is good for review.

2021-03-21 17:41 UTC, morph166955 commented
@kaikreuzer I created #133 with the "other half".  I believe, once this PR is committed, that one should build cleanly and a bunch of lines should "disappear" from that as they won't be different (because they are merged in here).

2021-03-23 20:12 UTC, kaikreuzer requested changes
Thanks @morph166955.

I still see two separate features in this PR:
1. Introducing a new thread pool - I am not really sure to understand what the "RemoteListener" exactly is, what kind of requests it handles and why those requests require a newly introduced pool. If it causes deadlocks with outgoing requests from the main pool, wouldn't using the async pool for these requests solve the issue?
2. Disabling thread pools. As commented in the code, the current solution does not look right and it probably causes heavy GC load. Wouldn't it make more sense to go e.g. for a `Executors.newCachedThreadPool()`, which is unlimited and optimized for many short-lived tasks like the ones we are looking at here?

Overall, I do not understand from the description, which problem is exactly solved by (1) and which one by (2). You mention OOMs, but this sounds rather like a symptom of another problem like blocked threads.

2021-03-23 20:35 UTC, morph166955 commented on bundles/org.jupnp/src/main/java/org/jupnp/DefaultUpnpServiceConfiguration.java
> +    public ExecutorService getMulticastReceiverExecutor(String threadName) {
This was added to assist in troubleshooting down the line when in "single thread mode".  I found it incredibly helpful as I was working on finding the issue in openhab-core/#1886.  By sending the thread name, I could directly see in a thread dump and in logs what was happening and what was causing the load on the system.  The only way I found to identify which parts of the code were asking for the executor was to pass it as a string from the original call.  Once passed, if we don't pass it along at each step it gets lost before It is effectively unused when the threadpools are enabled.

2021-03-23 20:37 UTC, morph166955 commented on bundles/org.jupnp/src/main/java/org/jupnp/OSGiUpnpServiceConfiguration.java
> +    protected ExecutorService getMainExecutorService(String threadName) {
Let me answer this while I answer your question about the Remote Listener threadpool above.

2021-03-23 20:39 UTC, morph166955 commented on bundles/org.jupnp/src/main/java/org/jupnp/OSGiUpnpServiceConfiguration.java
> +        prop = properties.get("asyncThreadPool");
That's fine.  I can rename the variable.  I was looking at it more bluntly as "is the thread pool enabled or disabled".  As true was the default, and enabling the pool is default behavior, I would suggest we call it enableAsyncThreadPool so that we don't end up with some kind of double negative and confuse people.

2021-03-23 20:39 UTC, morph166955 commented on bundles/org.jupnp/src/main/java/org/jupnp/OSGiUpnpServiceConfiguration.java
> +
Will fix in the next commit

2021-03-23 20:39 UTC, morph166955 commented on bundles/org.jupnp/src/main/java/org/jupnp/mock/MockRouter.java
> +
Will fix in the next commit

2021-03-23 20:39 UTC, morph166955 commented on bundles/org.jupnp/src/main/java/org/jupnp/UpnpServiceConfiguration.java
> +    public Executor getRemoteListenerExecutor(String threadName);
Missed that one.  Will fix in the next commit

2021-03-23 20:42 UTC, morph166955 commented on bundles/org.jupnp/src/main/java/org/jupnp/OSGiUpnpServiceConfiguration.java
> +    private ExecutorService createNamedThread(String threadName) {
Just to make sure I'm clear with your comment, are you just wanting me to rename this to something like createNamedSingleThreadExecutor() or something like that for clarity?  The way I was looking at this was that it is an ExecutorService which contains a brand new SingleThreadExecutor which contains a single new Thread.

2021-03-23 21:05 UTC, kaikreuzer commented on bundles/org.jupnp/src/main/java/org/jupnp/OSGiUpnpServiceConfiguration.java
> +        prop = properties.get("asyncThreadPool");
As for `httpProxyPort` "-1" is used to disable it, I wonder if we might even follow the same line here and simply define "-1" for the thread pools as well. This would safe us 3 new parameters and be aligned with the other code.

2021-03-23 21:09 UTC, kaikreuzer commented on bundles/org.jupnp/src/main/java/org/jupnp/OSGiUpnpServiceConfiguration.java
> +    private ExecutorService createNamedThread(String threadName) {
See my main review comment above: I'd think something like a `Executors.newCachedThreadPool()` would be a much better solution - IF we need disabled thread pools at all, of which you still have to convince me.

2021-03-23 21:09 UTC, morph166955 commented
> 1. Introducing a new thread pool - I am not really sure to understand what the "RemoteListener" exactly is, what kind of requests it handles and why those requests require a newly introduced pool. If it causes deadlocks with outgoing requests from the main pool, wouldn't using the async pool for these requests solve the issue?

I created the RemoteListener pool as a byproduct of troubleshooting https://github.com/openhab/openhab-core/issues/1886.  As I was going through thread dumps it became apparent to me that the main threadpool was getting exhausted when a whole bunch of messages were sent simultaneously and they were waiting for replies before performing an action.  In the case of that issue, my system was sending several dozen UNSUBSCRIBE messages during shutdown and waiting for the valid reply from that before removing from the registry.  Because the threadpool was full, the system was unable to actually listen for the reply from the device and it would just sit for the 10 seconds and fail.  

There were four main calls, all in bundles/org.jupnp/src/main/java/org/jupnp/registry/RemoteItems.java that seemed to be the culprits (which are the four I change in the commit).  They were all asking for getRegistryListenerExecutor() which replies with mainExecutorService.  Further investigation also found that getAsyncProtocolExecutor() in bundles/org.jupnp/src/main/java/org/jupnp/transport/RouterImpl.java was also seeing periods of bursts.  Because I was seeing issues on both main and async, I decided to attempt to fix this by making an entirely standalone threadpool that was able to work in parallel to the other pools but just hold threads dealing with listening for replies from remote devices.  That way, there was no chance that we missed hearing messages come in from remote devices because of either pool being full.  As it used to be called RegistryListener, I opted to name this RemoteListener.  

> 2. Disabling thread pools. As commented in the code, the current solution does not look right and it probably causes heavy GC load. Wouldn't it make more sense to go e.g. for a `Executors.newCachedThreadPool()`, which is unlimited and optimized for many short-lived tasks like the ones we are looking at here?

I can definitely change the mechanism used.  I've found that my system seems to just "feel like it works better" when I let it spin free of the pool constraint.  In my case, I have plenty of memory and cpu so I don't have a direct reason to restrain my system.  There are 1000% reasons to have threadpools and to leave them enabled as defaults which is why I didn't suggest pulling them out.  This mechanism effectively gives those who want to just let the system grow as needed the ability to do so.

2021-03-23 21:13 UTC, morph166955 commented on bundles/org.jupnp/src/main/java/org/jupnp/OSGiUpnpServiceConfiguration.java
> +        prop = properties.get("asyncThreadPool");
That's easy enough to do.  Honestly I think I did it this way because of a comment you made in https://github.com/openhab/openhab-core/pull/2182 - "Wrt disabling the threadpool: I'd prefer to introduce a dedicated boolean configuration option instead of introducing an implicit semantic for "-1". Firstly, because it would be an explicit semantic for that option and secondly because I would want to avoid some threadpool configurations working differently than others. Since we have many configurable threadpools and (afaik) none of those work with "-1" for disabling them, it doesn't feel good to do an exception here." - I was working both PRs at the same time and just used the same logic on both.  I'm fine with making -1 disable here, easy enough.

2021-03-23 21:17 UTC, morph166955 commented on bundles/org.jupnp/src/main/java/org/jupnp/OSGiUpnpServiceConfiguration.java
> +    private ExecutorService createNamedThread(String threadName) {
I can see what I can come up with.  To the point of IF we need to, my point back would be "if some users want the ability to do this, and it doesn't impact the userbase to have the feature available, why not?"  I can say, as a user who has tried both, my system just feels like it runs better when I don't have pools enabled.  The worst case scenario here in my eyes is that someone flips on an advanced feature, it doesn't work on their system, and they just turn it back off.  By no means am I suggesting that this become a default.  If it would help, I would be happy to have an alert pop up when the system is in this mode and say "You are using an advanced thread configuration, proceed at your own risk!"

2021-03-23 21:19 UTC, kaikreuzer commented on bundles/org.jupnp/src/main/java/org/jupnp/OSGiUpnpServiceConfiguration.java
> +        prop = properties.get("asyncThreadPool");
Yes, I remember that comment of mine. That's why I mentioned here to be "in line with the other code/parameters". While in openHAB, we have many pools and nowhere use a -1, here we already use -1 for other params and will treat all pools in the very same way.

2021-03-23 21:21 UTC, kaikreuzer commented on bundles/org.jupnp/src/main/java/org/jupnp/OSGiUpnpServiceConfiguration.java
> +    private ExecutorService createNamedThread(String threadName) {
>  I can say, as a user who has tried both, my system just feels like it runs better when I don't have pools enabled.

My point is that I'd like to understand the reason for it and not blindly add "features" that change some behavior, so that everyone has to try&pray and go for an option that seems to work, while nobody can really explain why.

2021-03-23 21:35 UTC, kaikreuzer commented
> Because the threadpool was full, the system was unable to actually listen for the reply from the device and it would just sit for the 10 seconds and fail.

So just to understand that correctly: The pool runs full with threads that do a request and they all wait for a response. Is that response really a direct response to the issued request (which I would expect to happen in the same thread) or is it a request issued by the remote device and containing the answer to "our" previous request?

> They were all asking for getRegistryListenerExecutor() which replies with mainExecutorService

Have you tried changing them to the asyncExecutorService to see if this solves the deadlock?

>  just hold threads dealing with listening for replies from remote devices

So this new pool deals with all the "culprits". What tells us that this new pool will have exactly the same problem as the main pool before? What makes the difference?

2021-03-23 21:48 UTC, morph166955 commented
> So just to understand that correctly: The pool runs full with threads that do a request and they all wait for a response. Is that response really a direct response to the issued request (which I would expect to happen in the same thread) or is it a request issued by the remote device and containing the answer to "our" previous request?

That is what I was observing yes.  I could see the first few UNSUBSCRIBE messages, and their responses, flying through.

I would point you to 

https://github.com/openhab/openhab-core/issues/1886#issuecomment-766169434

and

https://github.com/openhab/openhab-core/issues/1886#issuecomment-766177580 

for an enormous amount of debugs that led me to this.  The abridged version is logs like:

```
2021-01-23 13:51:23.308 [TRACE] [pnp.protocol.sync.SendingUnsubscribe] - Sending unsubscribe request: (OutgoingUnsubscribeRequestMessage) UNSUBSCRIBE http://REDACTED176:1400/MediaRenderer/RenderingControl/Event
2021-01-23 13:51:23.308 [DEBUG] [org.jupnp.transport.Router          ] - Sending via TCP unicast stream (request number 3857): (OutgoingUnsubscribeRequestMessage) UNSUBSCRIBE http://REDACTED176:1400/MediaRenderer/RenderingControl/Event
2021-01-23 13:51:23.308 [TRACE] [org.jupnp.transport.spi.StreamClient] - Preparing HTTP request: (OutgoingUnsubscribeRequestMessage) UNSUBSCRIBE http://REDACTED176:1400/MediaRenderer/RenderingControl/Event
2021-01-23 13:51:23.308 [TRACE] [org.jupnp.transport.spi.StreamClient] - Creating HTTP request. URI: 'http://REDACTED176:1400/MediaRenderer/RenderingControl/Event' method: 'UNSUBSCRIBE'
2021-01-23 13:51:23.308 [TRACE] [org.jupnp.transport.spi.StreamClient] - Waiting 10 seconds for HTTP request to complete: (OutgoingUnsubscribeRequestMessage) UNSUBSCRIBE http://REDACTED176:1400/MediaRenderer/RenderingControl/Event
2021-01-23 13:51:33.309 [INFO ] [org.jupnp.transport.spi.StreamClient] - Timeout of 10 seconds while waiting for HTTP request to complete, aborting: (OutgoingUnsubscribeRequestMessage) UNSUBSCRIBE http://REDACTED176:1400/MediaRenderer/RenderingControl/Event
2021-01-23 13:51:33.309 [WARN ] [org.jupnp.registry.Registry         ] - Removing (SID: uuid:RINCON_7828CA17095601400_sub0000000934) (RemoteService) Descriptor: /xml/RenderingControl1.xml
2021-01-23 13:51:33.309 [WARN ] [org.jupnp.registry.Registry         ] - Unlocking
```

which happens after waiting 10 seconds.  
 
> Have you tried changing them to the asyncExecutorService to see if this solves the deadlock?

Yes.  I would point you to the same debug above.  The async service also fills up in these bursty periods.  Of course we could dial either pool up substantially higher to resolve this, but that really doesn't fix anything and somewhat defeats the purpose of a threadpool in my opinion.
 
> So this new pool deals with all the "culprits". What tells us that this new pool will have exactly the same problem as the main pool before? What makes the difference?

So my theory is that we're going to end up at 1:1 on threads between main/async and remote.  When a message is sent, and we're going to wait on it, then in theory we should create a remote listener in that pool to line up with the original calling thread that's waiting for a response.  In theory, we shouldn't be able to even send a message, let alone wait for it, if either main or async are full.  The only thing I can think of that would have a problem is if we send a huge burst of messages in both main and async at the same time and we completely exhaust remote.  To fix this, we probably should have remote be larger than main and async (but not necessarily main + async because I think that's not necessary either).

2021-03-23 23:10 UTC, morph166955 commented on bundles/org.jupnp/src/main/java/org/jupnp/OSGiUpnpServiceConfiguration.java
> +        prop = properties.get("asyncThreadPool");
Fine by me.  I'll adjust the code to have -1 disable the pool.  I think I still have that code somewhere so it should be a copy/paste.

2021-03-23 23:22 UTC, morph166955 commented on bundles/org.jupnp/src/main/java/org/jupnp/OSGiUpnpServiceConfiguration.java
> +    private ExecutorService createNamedThread(String threadName) {
While the "end user experience/feeling" is likely subjective, I believe it's a direct result of there being no queue mechanism happening at all.  By disabling the thread pools we hand an executor/thread to the calling function immediately at all times.  Effectively "as fast as the system can do it, always."  The sacrifice is obviously increased memory usage.  By using a pool we are introducing a delay when the pool is full and we have to queue will slow down the operation of the system overall.  That's not to imply there is anything wrong with that, it's just a function of using a pool.  In my case, my OH is running on a VM on a relatively powerful hypervisor.  CPU and RAM are not an issue for me.  I don't mind giving a few extra meg to the process to avoid queueing.  

So to your point, I don't believe that this is a try and pray.  I believe that the system will work "just fine" with threadpools for most users.  A few may have to adjust their pool sizes if they have large UPnP environments, but it will work.  I also believe, from what's about two months of usage now on large non-pooled, that there is a performance benefit for those with systems that can handle it to be able to operate in a pool-less environment.  I'd consider this the ability to "hit the turbo button" on the system if that's what you want to do.

2021-03-23 23:32 UTC, morph166955 commented on bundles/org.jupnp/src/main/java/org/jupnp/OSGiUpnpServiceConfiguration.java
> +    private ExecutorService createNamedThread(String threadName) {
I'll add one more thing I just remembered. I put the single thread code in originally to help me find the root cause of the problems that I was seeing. Not for the purposes of performance. I also added the threadName for the same reason. It allowed me to really get into the weeds of the operation of my network and see the bursts happening. So on top of the performance gains, it helped with troubleshooting.

2021-03-24 01:22 UTC, morph166955 commented on bundles/org.jupnp/src/main/java/org/jupnp/mock/MockRouter.java
> +
Fixed

2021-03-24 01:22 UTC, morph166955 commented on bundles/org.jupnp/src/main/java/org/jupnp/UpnpServiceConfiguration.java
> +    public Executor getRemoteListenerExecutor(String threadName);
Fixed

2021-03-24 01:22 UTC, morph166955 commented on bundles/org.jupnp/src/main/java/org/jupnp/OSGiUpnpServiceConfiguration.java
> +
Fixed

2021-03-24 01:24 UTC, morph166955 commented on bundles/org.jupnp/src/main/java/org/jupnp/OSGiUpnpServiceConfiguration.java
> +        prop = properties.get("asyncThreadPool");
I believe this should be fixed.  I need to test it a little bit to validate 100%.

2021-03-24 02:14 UTC, morph166955 commented on bundles/org.jupnp/src/main/java/org/jupnp/OSGiUpnpServiceConfiguration.java
> +    private ExecutorService createNamedThread(String threadName) {
I went through the docs found at https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Executors.html in respect to Executors.  I concur with your suggestion to use newCachedThreadPool instead of newSingleThreadExecutor from the perspective of performance.  Not creating new threads will definitely be faster once the system gets up and going.  However, by using newCachedThreadPool we lose the benefits of having specific named threads for troubleshooting that we get by using newSingleThreadExecutor. To that end, I see two options

1) Leave it as is, so that we can continue to use named threads.
2) Remove all aspects of named threads and migrate to newCachedThreadPool.  This would be easily done as part of createExecutorServices().

My personal preference is option 1.  I believe there is great value in the named threads when trying to characterize the UPnP network.  It certainly helped me figure out what was going on after two years of fumbling around trying to understand why some of my devices would "just randomly act funny and die."  While you are 100% correct, we will be creating some additional overhead by constantly creating new threads/executors instead of using a cached pool, I'm not sure that the overhead will be noticeable to an end user (will it even be more than 1-2ms?).

Thoughts?

2021-03-24 02:20 UTC, morph166955 commented
I will pose a suggestion after reading the Executors docs again.  I would suggest that the RemoteListner pool be converted from a fixed size pool to a newCachedThreadPool.  If we're going to hold my theory true, then in theory that thread pool will only grow if and when needed based on calls in either main or async.  It should, in theory, never grow larger than main + async so we shouldn't ever run into an issue where it grows out of control.  That said, if we end up exhausting RemoteListener because we set it too small, then we are back in the same boat.

2021-03-27 02:49 UTC, morph166955 commented
I've rebased this from the current jupnp:master and resolved the conflicts.  I haven't tested the jar yet, but the code changes from the rebase didn't really do anything so everything should still work.  @kaikreuzer let me know what you think.

2021-03-28 18:40 UTC, morph166955 commented
I did some testing in respect to using newCachedThreadPool for the remote pool.  I implemented it as:

```
    private ExecutorService createRemoteProtocolExecutorService() {
        return Executors.newCachedThreadPool(new ThreadFactory() {

            @Override
            public Thread newThread(Runnable runnable) {
                    Thread thread = new Thread(runnable, "upnp-remote");
                    thread.setUncaughtExceptionHandler(new UncaughtExceptionHandler() {

                    @Override
                    public void uncaughtException(Thread thread, Throwable exception) {
                            throw new IllegalStateException(exception);
                    }
                    });
                    return thread;
            }
        });
    }

```

I've run a few tests on it.  The largest it grew (that I could catch) was 32 threads.  It nominalized out between 9 and 12 after 60 seconds.  It got down to 3 after a little longer (I think 90 seconds).

```
"upnp-remote-1" #873 prio=5 os_prio=0 cpu=0.68ms elapsed=55.85s tid=0x00007f384c0ac800 nid=0x1e6e48 waiting on condition  [0x00007f382c8d7000]
"upnp-remote-2" #874 prio=5 os_prio=0 cpu=2.75ms elapsed=55.84s tid=0x00007f3854faa800 nid=0x1e6e49 waiting on condition  [0x00007f3831826000]
"upnp-remote-3" #875 prio=5 os_prio=0 cpu=2.55ms elapsed=55.85s tid=0x00007f38577ba800 nid=0x1e6e4a waiting on condition  [0x00007f383606c000]
"upnp-remote-4" #877 prio=5 os_prio=0 cpu=8.94ms elapsed=55.84s tid=0x00007f3857977000 nid=0x1e6e4b waiting on condition  [0x00007f383c590000]
"upnp-remote-5" #879 prio=5 os_prio=0 cpu=1.84ms elapsed=55.84s tid=0x00007f3855c4b800 nid=0x1e6e4c waiting on condition  [0x00007f3831220000]
"upnp-remote-6" #881 prio=5 os_prio=0 cpu=6.06ms elapsed=55.84s tid=0x00007f3857978000 nid=0x1e6e4d waiting on condition  [0x00007f382cddc000]
"upnp-remote-7" #883 prio=5 os_prio=0 cpu=1.64ms elapsed=55.84s tid=0x00007f38559b7800 nid=0x1e6e4e waiting on condition  [0x00007f3831624000]
"upnp-remote-8" #885 prio=5 os_prio=0 cpu=1.04ms elapsed=55.84s tid=0x00007f385705d000 nid=0x1e6e4f waiting on condition  [0x00007f3831a28000]
"upnp-remote-9" #886 prio=5 os_prio=0 cpu=1.08ms elapsed=55.84s tid=0x00007f385705d800 nid=0x1e6e50 waiting on condition  [0x00007f3831523000]
"upnp-remote-10" #889 prio=5 os_prio=0 cpu=16.54ms elapsed=55.83s tid=0x00007f385705e800 nid=0x1e6e51 waiting on condition  [0x00007f3830d1b000]
"upnp-remote-11" #891 prio=5 os_prio=0 cpu=13.53ms elapsed=55.83s tid=0x00007f3855fff800 nid=0x1e6e52 waiting on condition  [0x00007f3830e1c000]
"upnp-remote-12" #893 prio=5 os_prio=0 cpu=25.33ms elapsed=55.83s tid=0x00007f38556d6800 nid=0x1e6e53 waiting on condition  [0x00007f3830f1d000]
"upnp-remote-13" #895 prio=5 os_prio=0 cpu=11.36ms elapsed=55.83s tid=0x00007f38556d7000 nid=0x1e6e54 waiting on condition  [0x00007f383101e000]
"upnp-remote-14" #897 prio=5 os_prio=0 cpu=7.97ms elapsed=55.83s tid=0x00007f3857265000 nid=0x1e6e55 waiting on condition  [0x00007f383111f000]
"upnp-remote-15" #899 prio=5 os_prio=0 cpu=1.38ms elapsed=55.83s tid=0x00007f3857266000 nid=0x1e6e56 waiting on condition  [0x00007f383cc91000]
"upnp-remote-16" #901 prio=5 os_prio=0 cpu=9.54ms elapsed=55.83s tid=0x00007f385441f000 nid=0x1e6e57 waiting on condition  [0x00007f3831321000]
"upnp-remote-17" #903 prio=5 os_prio=0 cpu=1.52ms elapsed=55.83s tid=0x00007f385441f800 nid=0x1e6e58 waiting on condition  [0x00007f383c48f000]
"upnp-remote-18" #905 prio=5 os_prio=0 cpu=7.04ms elapsed=55.83s tid=0x00007f3854420800 nid=0x1e6e59 waiting on condition  [0x00007f3831422000]
"upnp-remote-19" #907 prio=5 os_prio=0 cpu=6.37ms elapsed=55.83s tid=0x00007f3855e46800 nid=0x1e6e5a waiting on condition  [0x00007f382e8f7000]
"upnp-remote-20" #909 prio=5 os_prio=0 cpu=1.81ms elapsed=55.83s tid=0x00007f3855ff5800 nid=0x1e6e5b waiting on condition  [0x00007f3831f2d000]
"upnp-remote-21" #911 prio=5 os_prio=0 cpu=1.07ms elapsed=55.82s tid=0x00007f3855c4a000 nid=0x1e6e5c waiting on condition  [0x00007f3835965000]
"upnp-remote-22" #913 prio=5 os_prio=0 cpu=2.68ms elapsed=55.82s tid=0x00007f385461e000 nid=0x1e6e5d waiting on condition  [0x00007f383d396000]
"upnp-remote-23" #915 prio=5 os_prio=0 cpu=1.97ms elapsed=55.82s tid=0x00007f385461f000 nid=0x1e6e5e waiting on condition  [0x00007f383cd92000]
"upnp-remote-24" #917 prio=5 os_prio=0 cpu=0.39ms elapsed=55.82s tid=0x00007f3854c42000 nid=0x1e6e5f waiting on condition  [0x00007f383b382000]
"upnp-remote-25" #919 prio=5 os_prio=0 cpu=2.68ms elapsed=55.82s tid=0x00007f3854c43000 nid=0x1e6e60 waiting on condition  [0x00007f383a5db000]
"upnp-remote-26" #921 prio=5 os_prio=0 cpu=4.09ms elapsed=55.82s tid=0x00007f38545c1000 nid=0x1e6e61 waiting on condition  [0x00007f3836470000]
"upnp-remote-27" #923 prio=5 os_prio=0 cpu=0.35ms elapsed=55.82s tid=0x00007f38545c2000 nid=0x1e6e62 waiting on condition  [0x00007f3835a68000]
"upnp-remote-28" #925 prio=5 os_prio=0 cpu=0.41ms elapsed=55.82s tid=0x00007f3854c44000 nid=0x1e6e63 waiting on condition  [0x00007f383535f000]
"upnp-remote-29" #927 prio=5 os_prio=0 cpu=0.41ms elapsed=55.82s tid=0x00007f3856000800 nid=0x1e6e64 waiting on condition  [0x00007f383525e000]
"upnp-remote-30" #929 prio=5 os_prio=0 cpu=0.45ms elapsed=55.82s tid=0x00007f3856001000 nid=0x1e6e65 waiting on condition  [0x00007f383515d000]


"upnp-remote-4" #877 prio=5 os_prio=0 cpu=8.94ms elapsed=77.25s tid=0x00007f3857977000 nid=0x1e6e4b waiting on condition  [0x00007f383c590000]
"upnp-remote-6" #881 prio=5 os_prio=0 cpu=8.56ms elapsed=77.25s tid=0x00007f3857978000 nid=0x1e6e4d waiting on condition  [0x00007f382cddc000]
"upnp-remote-10" #889 prio=5 os_prio=0 cpu=16.54ms elapsed=77.25s tid=0x00007f385705e800 nid=0x1e6e51 waiting on condition  [0x00007f3830d1b000]
"upnp-remote-11" #891 prio=5 os_prio=0 cpu=13.53ms elapsed=77.25s tid=0x00007f3855fff800 nid=0x1e6e52 waiting on condition  [0x00007f3830e1c000]
"upnp-remote-12" #893 prio=5 os_prio=0 cpu=25.33ms elapsed=77.25s tid=0x00007f38556d6800 nid=0x1e6e53 waiting on condition  [0x00007f3830f1d000]
"upnp-remote-13" #895 prio=5 os_prio=0 cpu=11.36ms elapsed=77.24s tid=0x00007f38556d7000 nid=0x1e6e54 waiting on condition  [0x00007f383101e000]
"upnp-remote-14" #897 prio=5 os_prio=0 cpu=7.97ms elapsed=77.24s tid=0x00007f3857265000 nid=0x1e6e55 waiting on condition  [0x00007f383111f000]
"upnp-remote-16" #901 prio=5 os_prio=0 cpu=9.54ms elapsed=77.24s tid=0x00007f385441f000 nid=0x1e6e57 waiting on condition  [0x00007f3831321000]
"upnp-remote-18" #905 prio=5 os_prio=0 cpu=7.04ms elapsed=77.24s tid=0x00007f3854420800 nid=0x1e6e59 waiting on condition  [0x00007f3831422000]
"upnp-remote-19" #907 prio=5 os_prio=0 cpu=6.37ms elapsed=77.24s tid=0x00007f3855e46800 nid=0x1e6e5a waiting on condition  [0x00007f382e8f7000]
"upnp-remote-20" #909 prio=5 os_prio=0 cpu=1.81ms elapsed=77.24s tid=0x00007f3855ff5800 nid=0x1e6e5b waiting on condition  [0x00007f3831f2d000]


"upnp-remote-6" #881 prio=5 os_prio=0 cpu=12.55ms elapsed=111.81s tid=0x00007f3857978000 nid=0x1e6e4d waiting on condition  [0x00007f382cddc000]
"upnp-remote-11" #891 prio=5 os_prio=0 cpu=17.24ms elapsed=111.81s tid=0x00007f3855fff800 nid=0x1e6e52 waiting on condition  [0x00007f3830e1c000]
"upnp-remote-12" #893 prio=5 os_prio=0 cpu=26.35ms elapsed=111.80s tid=0x00007f38556d6800 nid=0x1e6e53 waiting on condition  [0x00007f3830f1d000]

```

I think it would definitely be a good idea to implement this for the remote thread pool irrespective of if we do single thread as an option for this.  Thoughts?

2021-04-03 22:13 UTC, morph166955 commented
I've done some long term testing on this and have found a few interesting oddities depending on configuration.

When running as committed, remoteThreadPool must be at least main + async in size otherwise there is a contention issue (e.g. I had it set to 15 - main, 30 - async, 20 - remote) as observed before (same exact issue actually where we run out of threads and we hit the whole "waiting 10 seconds" thing).  So there needs to be some kind of logic to not allow that to be lower than main + async.  Also, if either main or async is set to run in single thread mode, remote should also be in single thread mode.

cached thread pools seem to cause some issues.  I'm not entirely sure why, but when I have the cached code in place, things seem to cascade fail when any upnp device falls off the network.  For example, I unplugged one of my sonos speakers and within about 5 minutes every single device fell off (not all at once).  The only fix was restarting.  It could definitely be related to my implementation, but I have no idea why.

There were no issuses observed when all 3 were in single thread mode.

So I propose the following:
1) Remove the remoteThreadPool config entirely so that the user can't break the logic and cause issues.
2) If in threadpool mode, remoteThreadPool should equal main + async.
3) If either main or async are in single thread mode, remote is set to single.
4) Not go with the cached thread pools in this PR as it seems to cause problems.  I can continue to investigate and change this in a follow-on PR.  There is definitely reasons to do it, I just don't want that holding up this being committed.

Thoughts?

2021-04-04 20:27 UTC, morph166955 commented
I've created a test JAR for anyone following this who wants to try it out.  The JAR also includes the fixes from #133 and #135 for those who want to test it all out.

https://github.com/morph166955/jupnp/releases/tag/2.6.0-merge-129-133-135

2021-04-07 21:01 UTC, kaikreuzer commented
> cached thread pools seem to cause some issues.

Did you use them with an unlimited size or did you set a max size of them?
IIRC, these pools have the problem that if they reach their max size, they do not accept any new tasks and throw exceptions instead. That was the main reason, why the [custom thread pool](https://github.com/jupnp/jupnp/pull/47) had been created for jUPnP.

Wrt the remoteThreadPool, this still feels to me as if it is addressing symptoms and not the root cause. I cannot yet grasp what leads to the deadlocks and would still hope that they can be solved in some other way.
Have you ever done a thread dump to see what all the threads are waiting for and where we have a cycle that causes the deadlock?

2021-04-07 21:42 UTC, morph166955 commented
I let the cached thread pools run unlimited.  I saw them get very large in some focal testing (I drove it to over 150 threads) so I don't think I'm hitting a limit.

This is going to sound odd, but the problem is when we have an odd number!  Let's assume the async pool is set to 20.  Let's assume there are 10 other processes doing something, leaving 10 for functions to call and then wait for a reply.  This works just fine.  5 calls are made, 5 new threads to listen for the reply.  The reply happens, and effectively 2 threads are freed.  Now the problem.  Let's assume there are 9 processes, not 10.  Again, 5 calls are made, 5 new threads listen.  Then the 6th call is made, but there is no thread available for the reply to hear back on.  That 6th call dies after 10 seconds because there was no thread listening for the reply.  Now, worst case scenario (which is what happens on my network, and seems to happen during shutdown of OH3).  We get a whole bunch of calls all at once.  It is not true that a call is made and that a listener thread happens "immediately".  I have seen instances where I'll see a bunch of calls happen and then all the listeners are created sprinkled in.  So back to the analogy.  10 threads "doing something".  7 simultaneous calls.  The first two get a listener randomly, the third gets one in the last slot, the others don't and have to die at the 10 second mark.  Then one by one the other calls happen and the system just gets completely jammed up.  

This is why the single threaded mode "just works".  There is never a point where you get these odd numbered things happening.  There is just always space.  This should also have been the case with the cached thread pool, and I just don't know enough about them to really understand why having it in there caused problems.  I'm assuming it was likely related to my implementation and maybe some kind of uncaught exception or something like that which I wasn't seeing in the logs.

2021-04-08 02:15 UTC, morph166955 commented
I removed the user ability to adjust remoteThreadPool and based it off of the settings for main and async.  This prevents a user from creating a problem by improperly sizing or configuring the pool.

2021-04-08 22:13 UTC, morph166955 commented
Almost 24 hours running the updated code.  Nothing to report.  The only device state flaps were caused by my samsung TVs actually turning on/off so expected behavior.

2021-05-15 18:49 UTC, kaikreuzer commented on bundles/org.jupnp/src/main/java/org/jupnp/OSGiUpnpServiceConfiguration.java
> +    private ExecutorService createNamedThread(String threadName) {
While I understand that the named threads were helpful for analysis, my [very first comment on this PR](https://github.com/jupnp/jupnp/pull/129/files#r599881695) was already that it makes the code unlogical and somewhat dirty.

I'd hence very much plead for option 2 here.

2021-05-23 23:05 UTC, morph166955 commented on bundles/org.jupnp/src/main/java/org/jupnp/OSGiUpnpServiceConfiguration.java
> +    private ExecutorService createNamedThread(String threadName) {
@kaikreuzer No issues then here with going with option 2.  My only problem right now, I have no way to actually commit the change to implement this.  My dev system is entirely down right now because I moved.  It will likely be several days if not weeks before I can commit the change and test it.  If you have the ability to make the change, I would greatly appreciate it.

2021-05-24 08:31 UTC, kaikreuzer commented on bundles/org.jupnp/src/main/java/org/jupnp/OSGiUpnpServiceConfiguration.java
> +    private ExecutorService createNamedThread(String threadName) {
I'll see if I find an easy way to do it the next days. If not, I'll leave it for you, once your are back in working mode.

2021-05-27 21:03 UTC, kaikreuzer commented
@morph166955 I have changed the PR as discussed and created #138 as a follow-up.

2021-05-27 21:03 UTC, closed without merging