Adds StreamClientConfiguration to createStreamClient
jupnp/jupnp pull request #134
Opened 2021-03-24 22:01 UTC by morph166955

Adds StreamClientConfiguration to createStreamClient 

This allows the passing of different configuration variables without having to make changes in so many places when one is added.

2021-03-24 22:05 UTC, morph166955 commented
@kaikreuzer I opted to pull this out of https://github.com/jupnp/jupnp/pull/133 based on your comment there.  If you can commit this in, I can definitively split https://github.com/jupnp/jupnp/pull/133 and https://github.com/jupnp/jupnp/pull/129 so that they can stand on their own.  Then we can work each one separately and not have one rely on the other.

My only question, I did this as StreamClientConfig instead of StreamClientConfigImpl.  I believe that should be fine, and it compiles without issue.  I did note one place in the code where StreamClientConfigImpl was used instead of StreamClientConfig which is the only reason I'm even asking.

2021-03-24 22:33 UTC, kaikreuzer requested changes
That makes sense, thanks. Just some minor formatting corrections required.

2021-03-24 22:33 UTC, kaikreuzer commented on bundles/org.jupnp/src/main/java/org/jupnp/DefaultUpnpServiceConfiguration.java
> +        return transportConfiguration.createStreamClient(getSyncProtocolExecutorService(),configuration);
```suggestion
        return transportConfiguration.createStreamClient(getSyncProtocolExecutorService(), configuration);
```

2021-03-24 22:33 UTC, kaikreuzer commented on bundles/org.jupnp/src/main/java/org/jupnp/OSGiUpnpServiceConfiguration.java
> +        return transportConfiguration.createStreamClient(getSyncProtocolExecutorService(),configuration);
```suggestion
        return transportConfiguration.createStreamClient(getSyncProtocolExecutorService(), configuration);
```

2021-03-24 22:33 UTC, kaikreuzer commented on tests/core/src/test/java/org/jupnp/test/transport/JettyServerJettyClientTest.java
> +                configuration.getSyncProtocolExecutorService(),sccConfiguration
```suggestion
                configuration.getSyncProtocolExecutorService(), sccConfiguration
```

2021-03-24 22:33 UTC, kaikreuzer commented on tools/org.jupnp.tool/src/main/java/org/jupnp/tool/cli/CmdlineUPnPServiceConfiguration.java
> +                getSyncProtocolExecutorService(),configuration
```suggestion
                getSyncProtocolExecutorService(), configuration
```

2021-03-24 22:36 UTC, kaikreuzer commented on tools/org.jupnp.tool/src/main/java/org/jupnp/tool/cli/CmdlineUPnPServiceConfiguration.java
> +        private StreamClientConfiguration configuration;
```suggestion
    private StreamClientConfiguration configuration;
```

2021-03-24 22:38 UTC, kaikreuzer approved these changes

2021-03-24 22:40 UTC, merged

2021-03-24 22:41 UTC, morph166955 commented
Thank you!  I'll rebase the other two and split them apart.

2021-03-27 03:16 UTC, morph166955 commented
@kaikreuzer apparently this created a null pointer exception.  I believe we have a chicken and the egg problem.  I believe that we need to add "new StreamClientConfiguration()" however that requires us to send it the executor service when creating it which isn't yet created.  If we send it before we read the configs, we won't be able to properly create the threadpool (or single-thread) because we won't know if the user changed the configuration for those pools yet.  I hadn't noticed this until I went to test the retryAfterSeconds code which actually uses this when pulling configurations in from the OSGi.

2021-03-27 03:43 UTC, morph166955 commented
2021-03-27 02:59:35.605 [ERROR] [org.jupnp                           ] - bundle org.jupnp:2.6.0.202103270250 (216)[org.jupnp(282)] : The activate method has thrown an exception
java.lang.NullPointerException: null
        at org.jupnp.OSGiUpnpServiceConfiguration.createConfiguration(OSGiUpnpServiceConfiguration.java:488) ~[?:?]
        at org.jupnp.OSGiUpnpServiceConfiguration.activate(OSGiUpnpServiceConfiguration.java:154) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]

Where 488 was:

log.info("OSGiUpnpServiceConfiguration createConfiguration retryAfterSeconds = {}", configuration.getRetryAfterSeconds());

2021-03-27 04:23 UTC, morph166955 commented
https://github.com/jupnp/jupnp/pull/135 submitted to fix the NPE caused with this.