Modernize library
jupnp/jupnp pull request #155
Opened 2023-09-11 21:09 UTC by wborn

* Use Java 11 as compiler source and target
* Replace tycho with bnd
* Use DS annotations
* Upgrade Maven plug-ins
* Upgrade dependencies
* Set project version to 3.0.0-SNAPSHOT
* Ignore IDE generated files in .gitignore
* Remove Eclipse generated files
* Add sortpom-maven-plugin
* Sort and cleanup POMs
* Migrate JUnit 4 tests to JUnit 5
* Migrate TestNG tests to JUnit 5

2023-09-18 17:21 UTC, wborn commented
Perhaps you can review these changes @kaikreuzer?
The changes should make it easier to maintain and contribute to the library.
It should now also be more easy to work on the code in IDEs like IntelliJ and VS Code.
I also successfully tested the changes with openHAB. :slightly_smiling_face: 

It's probably best to merge this without squashing the commits.

After the PR is merged I will probably do some more code cleanup/reformatting but this PR already got quite big!

2023-11-25 13:30 UTC, wborn commented
Maybe you can find some time to review this @kaikreuzer?

2023-12-05 21:28 UTC, kaikreuzer commented
I'll try to do this after christmas (and the openHAB 4.1 release) - looks like a huge work that you did here!

2024-01-06 09:29 UTC, wborn commented
This PR would be a great way to update jupnp into a 2024 tech landscape @kaikreuzer. 😉

2024-01-06 10:34 UTC, kaikreuzer commented
Absolutely! Thanks for the ping, I'll try to find time for it asap.

2024-01-06 23:31 UTC, kaikreuzer requested changes
Thanks, this is a wonderful update!
Looks all very familiar to the openHAB build now. :-)

Running the build locally, I get two test errors:
```
[ERROR] Errors: 
[ERROR]   InvalidUDA10DeviceDescriptorParsingTest.readRecovering:139->readDevice:153 » DescriptorBinding Could not parse device descriptor: org.xml.sax.SAXParseException; lineNumber: 19; columnNumber: 21; Präfix "dlna" für Element "dlna:X_DLNADOC" ist nicht gebunden.
[ERROR]   InvalidUDA10DeviceDescriptorParsingTest.readRecovering:139->readDevice:153 » DescriptorBinding Could not parse device descriptor: org.xml.sax.SAXParseException; lineNumber: 19; columnNumber: 21; Präfix "dlna" für Element "dlna:X_DLNADOC" ist nicht gebunden.
[INFO] 
[ERROR] Tests run: 336, Failures: 0, Errors: 2, Skipped: 2
```
Do you have the same or is there anything wrong in my local setup?

2024-01-06 23:31 UTC, kaikreuzer commented on bundles/org.jupnp/src/main/java/org/jupnp/transport/impl/jetty/JettyServletContainer.java
> +        ServerConnector connector = new ServerConnector(server);
This change does not look to be related to its commit "Migrate TestNG tests to JUnit 5"...
Is this a bug fix for some issue?

2024-01-06 23:31 UTC, kaikreuzer commented on tests/integration/itest.bndrun
> +	org.jupnp;version='[3.0.0,3.0.1)',\
Do we need to re-resolve those upon JUPnP version changes? Could you add something to the README on how to do this?

2024-01-06 23:31 UTC, kaikreuzer commented on tools/org.jupnp.tool/src/main/java/org/jupnp/tool/cli/CmdlineUPnPServiceConfiguration.java
>      private ExecutorService asyncExecutorService;
This line seems to have spaces instead of tabs - could you fix this?

2024-01-07 10:16 UTC, wborn commented on bundles/org.jupnp/src/main/java/org/jupnp/transport/impl/jetty/JettyServletContainer.java
> +        ServerConnector connector = new ServerConnector(server);
I found it was required for fixing the `JettyServerJettyClientTest` (https://github.com/jupnp/jupnp/issues/119#issuecomment-1715819128), you'll see it fail without that change. That test currently does not fail because it does not run by default, see [AllTests.tng.xml](https://github.com/jupnp/jupnp/blob/4a3ab9dec37cb9be324d02f6dc81ffca74237e1e/tests/core/src/test/AllTests.tng.xml#L62-L78). IIRC it is also required for the OSGi integratation tests which currently are also do not run.

2024-01-07 10:16 UTC, wborn commented on tests/integration/itest.bndrun
> +	org.jupnp;version='[3.0.0,3.0.1)',\
There's some docs on this now. :+1:

2024-01-07 10:18 UTC, wborn commented on tools/org.jupnp.tool/src/main/java/org/jupnp/tool/cli/CmdlineUPnPServiceConfiguration.java
>      private ExecutorService asyncExecutorService;
Fixed! I still want to add Spotless and reformat the code because it uses a mix of tabs/spaces everywhere. But that is something for another PR. :wink:

2024-01-07 10:19 UTC, wborn commented
> Do you have the same or is there anything wrong in my local setup?

I think it may be local to your setup as it does not fail for me (and GitHub Actions) on Ubuntu.

2024-01-07 12:13 UTC, kaikreuzer approved these changes
lgtm, many thanks!

2024-01-07 12:13 UTC, merged